repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^scripts/ci/
      - id: trailing-whitespace
        exclude: ^scripts/ci/
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^scripts/ci/
      - id: ruff-format
        exclude: ^scripts/ci/

  - repo: local
    hooks:
      - id: enforce-python-version
        name: Enforce python3 version (configurable)
        entry: python3 scripts/ci/check_python_version.py
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: commit-msg-task-guard
        name: Enforce Task ID in commit message
        entry: python3 scripts/ci/commit_msg_task_guard.py
        language: system
        stages: [commit-msg]
        pass_filenames: true
