name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install ruff mypy pytest pytest-cov

      - name: Ruff Lint
        run: |
          ruff check .

      - name: Ruff Format (check only)
        run: |
          ruff format --check .

      - name: Mypy Typecheck
        run: |
          mypy .

      - name: Pytest
        run: |
          pytest -q
